
market-data:
  variables:
    urls:
      market-data: https://redbrokers-market-data.herokuapp.com
    exchange-url:
      one: https://exchange.matraining.com/md
      two: https://exchange2.matraining.com/md
    callback: "${market-data.variables.urls.market-data}/api/v1/callback/webhook"
    redis:
      topic: "pubsub:market-data"


spring:
  mvc:
    throw-exception-if-no-handler-found: true
#  redis:
#    port: ${REDIS_PORT}
#    host: ${REDIS_URL}
    url: ${REDIS_URL}
server:
  error:
    whitelabel:
      enabled: false