
market-data:
  test: lop
  variables:
    urls:
      market-data: https://redbrokers-market-data.herokuapp.com
    exchange-url:
      one: https://exchange.matraining.com/md
      two: https://exchange2.matraining.com/md
    callback: "${market-data.variables.urls.market-data}/api/v1/callback/webhook"
    redis:
      topic: "pubsub:market-data"


spring:
  mvc:
    throw-exception-if-no-handler-found: true
  redis:
    port: 19340
    host: ec2-52-3-86-34.compute-1.amazonaws.com
#    url: redis://:p0bcc3ba27d7a815d95c60c6c3bd0aba383cfd7a492e9fef8d5e3af60e23ebb25@ec2-52-3-86-34.compute-1.amazonaws.com:19339
server:
  error:
    whitelabel:
      enabled: false