
market-data:
  variables:
    exchange-url:
      one: https://exchange.matraining.com/md
      two: https://exchange2.matraining.com/md
    callback: ""


spring:
  mvc:
    throw-exception-if-no-handler-found: true
server:
  error:
    whitelabel:
      enabled: false